name: Build & deploy

on:
  push:
    branches:
      - master

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: main to s3
      run: bash scripts/pipeline/main.sh ${{secrets.new-one-bucket}} "index.html.txt" ${{secrets.ACCESSKEYID}} ${{secrets.SECRETACCESSKEY}} "index.html.txt"
